[2025-10-04T05:17:43.786+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
