[2025-10-03T07:54:11.279+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [None]>
[2025-10-03T07:54:11.912+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [None]>
[2025-10-03T07:54:11.958+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-03T07:54:12.500+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_sales_table> on 2025-10-02 00:00:00+00:00
[2025-10-03T07:54:12.812+0000] {standard_task_runner.py:60} INFO - Started process 389 to run task
[2025-10-03T07:54:12.863+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_revenue_pipeline', 'create_sales_table', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/sales_revenue_pipeline.py', '--cfg-path', '/tmp/tmp87tlnlbn']
[2025-10-03T07:54:13.039+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask create_sales_table
[2025-10-03T07:54:16.543+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [running]> on host dcf7c9b4a5d6
[2025-10-03T07:54:22.064+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_revenue_pipeline' AIRFLOW_CTX_TASK_ID='create_sales_table' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T07:54:23.553+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-10-03T07:54:23.679+0000] {sql.py:450} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS sales (
        id SERIAL PRIMARY KEY,
        order_date DATE NOT NULL,
        product_name VARCHAR(100),
        quantity INTEGER,
        unit_price DECIMAL(10,2),
        total_amount DECIMAL(10,2)
    );
    , parameters: None
[2025-10-03T07:54:23.985+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-10-03T07:54:24.095+0000] {sql.py:450} INFO - Running statement: DELETE FROM sales;, parameters: None
[2025-10-03T07:54:24.137+0000] {sql.py:459} INFO - Rows affected: 8
[2025-10-03T07:54:24.381+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-10-03T07:54:24.603+0000] {sql.py:450} INFO - Running statement: 
    INSERT INTO sales (order_date, product_name, quantity, unit_price, total_amount)
    VALUES 
        ('2024-01-01', 'Laptop', 2, 1500.00, 3000.00),
        ('2024-01-01', 'Mouse', 5, 25.50, 127.50),
        ('2024-01-02', 'Keyboard', 3, 75.00, 225.00),
        ('2024-01-02', 'Monitor', 1, 800.00, 800.00),
        ('2024-01-03', 'Laptop', 1, 1500.00, 1500.00),
        ('2024-01-03', 'Headphones', 4, 50.00, 200.00),
        ('2024-01-04', 'Tablet', 2, 600.00, 1200.00),
        ('2024-01-04', 'Mouse', 3, 25.50, 76.50);
    , parameters: None
[2025-10-03T07:54:24.717+0000] {sql.py:459} INFO - Rows affected: 8
[2025-10-03T07:54:24.763+0000] {logging_mixin.py:188} INFO - âœ… Sales table created and sample data inserted successfully
[2025-10-03T07:54:24.797+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-03T07:54:25.423+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=sales_revenue_pipeline, task_id=create_sales_table, execution_date=20251002T000000, start_date=20251003T075411, end_date=20251003T075425
[2025-10-03T07:54:25.843+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-03T07:54:26.240+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-03T17:49:12.336+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T17:49:12.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T17:49:12.454+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-03T17:49:12.553+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_sales_table> on 2025-10-02 00:00:00+00:00
[2025-10-03T17:49:12.671+0000] {standard_task_runner.py:60} INFO - Started process 257 to run task
[2025-10-03T17:49:12.873+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sales_revenue_pipeline', 'create_sales_table', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sales_revenue_pipeline.py', '--cfg-path', '/tmp/tmp6n0jo7gi']
[2025-10-03T17:49:13.033+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask create_sales_table
[2025-10-03T17:49:15.781+0000] {task_command.py:423} INFO - Running <TaskInstance: sales_revenue_pipeline.create_sales_table scheduled__2025-10-02T00:00:00+00:00 [running]> on host 06d653bd8bf1
[2025-10-03T17:49:16.842+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_revenue_pipeline' AIRFLOW_CTX_TASK_ID='create_sales_table' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T17:49:16.915+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sales_revenue_pipeline.py", line 32, in create_sales_table
    hook.run(create_table_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 128, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-10-03T17:49:16.952+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=sales_revenue_pipeline, task_id=create_sales_table, execution_date=20251002T000000, start_date=20251003T174912, end_date=20251003T174916
[2025-10-03T17:49:17.019+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task create_sales_table (The conn_id `postgres_default` isn't defined; 257)
[2025-10-03T17:49:17.079+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-03T17:49:17.180+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
